name: Flujo de trabajo para Issue
on:
  issues:
    types: [opened]
  project_card:
    types: [moved]
  workflow_dispatch:
jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      - name: Imprimir información
        run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Evento disparador: ${{ github.event_name }}"
          echo "Rama correspondiente: ${{ github.ref }}"
          echo "Versión del runner: ${{ runner.tool_cache }}"

