name: Flujo de trabajo para ejecutar los test
on:
  workflow_dispatch:
  push:
    branches: [ V.0.2 ]
  pull_request:
    branches: [ V.0.2 ]
  schedule:
    - cron: '1 23 * * 0-4'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: "juamemmen"
      
      GITHUB_PACKAGES: "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"
      GITHUB_OAUTH: "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"
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew assemble

  Test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      GITHUB_LOGIN: "juamemmen"
      GITHUB_PACKAGES: "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"
      GITHUB_OAUTH: "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"
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test